"""Regenerate mod_template.py from mod/bb_reroll_dump.nut.

Run this whenever you edit the .nut source so the embedded copy stays in
sync with the on-disk version.

Usage:  python tools/embed_nut.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NUT  = ROOT / "mod" / "bb_reroll_dump.nut"
OUT  = ROOT / "mod_template.py"

nut = NUT.read_text(encoding="utf-8").replace("\r\n", "\n")
assert "'''" not in nut, ".nut contains triple single quotes — change embed quote style"

OUT.write_text(
    '"""Embedded copy of mod/bb_reroll_dump.nut.\n'
    '\n'
    'Auto-generated by tools/embed_nut.py — re-run that script after editing the .nut\n'
    'so the GUI ships with the latest mod source baked in.\n'
    '"""\n'
    '\n'
    "NUT_TEMPLATE = r'''" + nut + "'''\n",
    encoding="utf-8",
)
print(f"Wrote {OUT.relative_to(ROOT)} ({len(nut)} chars of .nut)")
